# Generated by Django 5.0.6 on 2024-11-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_42_staf',
            field=models.BooleanField(default=False),
        ),
    ]
