# Generated by Django 5.0.6 on 2024-11-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_age_user_coalition_user_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coalition',
            field=models.JSONField(default=dict),
        ),
    ]
