# Generated by Django 5.0.6 on 2024-12-04 15:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_emailanswer_question_id_scalequestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='pregunta número')),
                ('text', models.CharField(max_length=320, verbose_name='Pregunta')),
                ('value', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('is_required', models.BooleanField(default=1, verbose_name='¿Respuesta requerida?')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form')),
            ],
            options={
                'db_table': 'Date question',
            },
        ),
        migrations.CreateModel(
            name='DateAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField()),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.answer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datequestion')),
            ],
        ),
    ]
