# Generated by Django 5.0.6 on 2024-12-04 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datequestion_dateanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='pregunta número')),
                ('text', models.CharField(max_length=320, verbose_name='Pregunta')),
                ('url', models.URLField(verbose_name='URL')),
                ('is_required', models.BooleanField(default=1, verbose_name='¿Respuesta requerida?')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form')),
            ],
            options={
                'db_table': 'URL question',
            },
        ),
        migrations.CreateModel(
            name='URLAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.URLField()),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.answer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.urlquestion')),
            ],
        ),
    ]
