# Generated by Django 5.0.6 on 2024-11-28 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_coalition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('favourite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='BooleanQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='pregunta número')),
                ('text', models.CharField(max_length=250, verbose_name='Pregunta')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form')),
            ],
            options={
                'db_table': 'Boolean question',
            },
        ),
        migrations.CreateModel(
            name='OptionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='pregunta número')),
                ('text', models.CharField(max_length=250, verbose_name='Pregunta')),
                ('options', models.JSONField(default=dict)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form')),
            ],
            options={
                'db_table': 'Option question',
            },
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='pregunta número')),
                ('text', models.CharField(max_length=250, verbose_name='Pregunta')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form')),
            ],
            options={
                'db_table': 'Text question',
            },
        ),
    ]
