# Generated by Django 5.0.6 on 2024-12-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_urlquestion_urlanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='pregunta número')),
                ('text', models.CharField(max_length=320, verbose_name='Pregunta')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Archivo')),
                ('is_required', models.BooleanField(default=1, verbose_name='¿Respuesta requerida?')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form')),
            ],
            options={
                'db_table': 'File question',
            },
        ),
        migrations.CreateModel(
            name='FileAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FileField(upload_to='uploads/')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.answer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filequestion')),
            ],
        ),
    ]
