# Generated by Django 5.0.6 on 2024-11-28 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_form_booleanquestion_optionquestion_textquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sended', models.DateTimeField(verbose_name='sended')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
