# Generated by Django 5.0.6 on 2024-11-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentform',
            name='answered',
            field=models.BooleanField(default=False, verbose_name='answered'),
        ),
    ]
